# Generated by Django 5.0.7 on 2024-07-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_is_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_login',
            field=models.BooleanField(default=False),
        ),
    ]
