# Generated by Django 5.0.7 on 2024-07-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_transaction_user_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='user_transa_deposit_38fa3d_idx',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['deposit_amount', 'withdraw_amount', 'transaction_type'], name='user_transa_deposit_13ab53_idx'),
        ),
    ]
