# Generated by Django 5.0.7 on 2024-07-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_transaction_user_transa_deposit_38fa3d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
