# Generated by Django 5.0.7 on 2024-08-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_transaction_get_balance'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='user_transa_deposit_13ab53_idx',
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['deposit_amount', 'withdraw_amount', 'transaction_type', 'get_balance'], name='user_transa_deposit_d319ec_idx'),
        ),
    ]
